### ISSUE TITLE
Project should be renamed

### ISSUE THREAD

**Issue by Petah** [PHLAK/Stash#1]
This is named the same as a very well known and used library: http://www.stashphp.com/

You should consider renaming it.

**Comment by PHLAK** [comment]
Isn't this is the point of Namespacing though? Not that I disagree with you but the packages `tedivm/stash` and `phlak/stash` can safely co-exist without issue.  However, now that you've brought it to my attention I will certainly _consider_ renaming it, pending my ability to come up with another name that's not only conflict free but that I also like. =/
