### ISSUE TITLE
Redis update function delete()

### ISSUE THREAD

**Issue by ghost** [PHLAK/Stash#7]
Hello,

after the last update, the Redis::delete() method in Drivers/Redis.php on line 197 is deprecated

I suggest changing line

`return $this->redis->delete($key) ? true : false;`

by

`return $this->redis->del($key) ? true : false;`

**Comment by PHLAK** [comment]
Thank you. Where did you see this? Can you provide a link to some documentation?

Edit: Found it: https://github.com/phpredis/phpredis#del-delete-unlink

> **Note:** `delete` is an alias for `del` and will be removed in future versions of phpredis.
